export const FORMATS = [
  {
    key: "clu",
    name: "Clu",
    isStates: false,
    suffix: "",
    extension: "clu",
  },
  {
    key: "tree",
    name: "Tree",
    isStates: false,
    suffix: "",
    extension: "tree",
  },
  {
    key: "ftree",
    name: "Ftree",
    isStates: false,
    suffix: "",
    extension: "ftree",
  },
  {
    key: "net",
    name: "Network",
    isStates: false,
    suffix: "",
    extension: "net",
  },
  {
    key: "states_as_physical",
    name: "States as physical",
    isStates: false,
    suffix: "_states_as_physical",
    extension: "net",
  },
  {
    key: "clu_states",
    name: "Clu",
    isStates: true,
    suffix: "_states",
    extension: "clu",
  },
  {
    key: "tree_states",
    name: "Tree",
    isStates: true,
    suffix: "_states",
    extension: "tree",
  },
  {
    key: "ftree_states",
    name: "Ftree",
    isStates: true,
    suffix: "_states",
    extension: "ftree",
  },
  {
    key: "states",
    name: "States",
    isStates: true,
    suffix: "_states",
    extension: "net",
  },
  {
    key: "flow",
    name: "Flow",
    isStates: false,
    suffix: "_flow",
    extension: "net",
  },
  {
    key: "flow_as_physical",
    name: "Flow states as physical",
    isStates: true,
    suffix: "_states_as_physical_flow",
    extension: "net",
  },
  {
    key: "newick",
    name: "Newick",
    isStates: false,
    suffix: "",
    extension: "nwk",
  },
  {
    key: "newick_states",
    name: "Newick",
    isStates: true,
    suffix: "_states",
    extension: "nwk",
  },
  {
    key: "json",
    name: "JSON",
    isStates: false,
    suffix: "",
    extension: "json",
  },
  {
    key: "json_states",
    name: "JSON",
    isStates: true,
    suffix: "_states",
    extension: "json",
  },
  {
    key: "csv",
    name: "CSV",
    isStates: false,
    suffix: "",
    extension: "csv",
  },
  {
    key: "csv_states",
    name: "CSV",
    isStates: true,
    suffix: "_states",
    extension: "csv",
  },
];
