import {
  Box,
  Button,
  Link as CkLink,
  Container,
  chakra,
  Flex,
  Grid,
  Heading,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import TeX from "@matejmazur/react-katex";
import type { NextPage } from "next";
import NextLink from "next/link";
import { useState } from "react";
import { LuArrowRight, LuCheck, LuCopy } from "react-icons/lu";
import * as exampleNetworks from "../data/networks";
import * as outputExamples from "../data/output";
import { infomapVersionLabel } from "../shared/infomapVersion";

const preview = (content: string, maxLines = 18) => {
  const lines = content.trim().split("\n");
  if (lines.length <= maxLines) return content.trim();
  return `${lines.slice(0, maxLines).join("\n")}\n# ...`;
};

const formats = [
  {
    id: "InputLinkList",
    chip: ".net",
    side: "input",
    title: "Link list",
    tag: "source target [weight]",
    description:
      "Use a link list for ordinary networks where each row is an edge. This is the simplest and most portable input format.",
    details: [
      "Each row is source target [weight]. The optional weight must be non-negative. Missing weights default to 1.",
      "If a file has no recognized header, Infomap treats it as a link list.",
    ],
    figures: [
      {
        src: "/infomap/images/nine-triangles.svg",
        alt: "Network of nine triangles",
        caption:
          "Network generated from a Sierpinski fractal of three levels with nine triangles at the bottom level. The optimal solution is not the symmetric case with three modules in each supermodule.",
      },
    ],
    example: preview(exampleNetworks.twoTriangles),
  },
  {
    id: "InputPajek",
    chip: ".net",
    side: "input",
    title: "Pajek",
    tag: "*Vertices + *Edges",
    description:
      "Use Pajek when you need a separate node section, node names, or compatibility with existing .net files.",
    details: [
      "The node section starts with *Vertices N and the link section with *Edges N, *Links N, or *Arcs N, where N is the number of nodes or links.",
      "Text inside quotation marks gives the node name. You can assign node weights by adding a third column with positive numbers. Links are interpreted like the link-list format.",
    ],
    example: preview(exampleNetworks.pajek),
  },
  {
    id: "InputBipartite",
    chip: ".net",
    side: "input",
    title: "Bipartite",
    tag: "*Bipartite",
    description:
      "Use bipartite input when links connect two different node types, such as users to items or documents to words.",
    details: [
      "By default, Infomap adjusts bipartite flow so modules are detected among the primary nodes without first projecting the network. This avoids creating a dense one-mode projection.",
      "The format uses *Bipartite N, where N is the first node id of the feature node type.",
    ],
    figures: [
      {
        src: "/infomap/images/bipartite.svg",
        alt: "Bipartite network with three round and two square nodes",
        caption:
          "Bipartite network with three primary nodes and two feature nodes.",
        maxW: "16rem",
      },
    ],
    example: preview(exampleNetworks.bipartite),
  },
  {
    id: "InputMultilayer",
    chip: ".net",
    side: "input",
    title: "Multilayer",
    tag: "*Multilayer / *Intra / *Inter",
    description:
      "Use multilayer input when the same physical node can appear in multiple layers and movement between layers matters.",
    details: [
      "Choose the format based on how much control you need over movement between layers. With *Multilayer, you specify all intra-layer and inter-layer links explicitly.",
      "With *Intra and *Inter, you specify intra-layer links and constrain movement between layers. With only *Intra, inter-layer links are generated automatically from the relax rate.",
    ],
    figures: [
      {
        src: "/infomap/images/multilayer-network-full.svg",
        alt: "Multilayer network",
        caption:
          "Full multilayer input with two layers and explicit links between layers.",
      },
      {
        src: "/infomap/images/multilayer-network-intra-inter.svg",
        alt: "Multilayer network in intra-inter format",
        caption:
          "Intra/inter-layer input, where relative inter-layer weights define layer-switching probabilities for each physical node.",
      },
      {
        src: "/infomap/images/multilayer-network-intra.svg",
        alt: "Multilayer network using inter-layer relaxation",
        caption:
          "Intra-layer input with inter-layer movement generated by relax rate.",
      },
    ],
    example: preview(exampleNetworks.multilayer, 20),
  },
  {
    id: "InputStates",
    chip: ".net",
    side: "input",
    title: "State network",
    tag: "*States",
    description:
      "Use state input for memory networks, multilayer networks, and advanced workflows where internal state nodes should be explicit.",
    details: [
      "The *States section describes internal nodes as state_id physical_id [name]. The state id is then referenced in the *Links section.",
      "The *Vertices section is optional and follows the Pajek format. It is used to name the physical nodes.",
    ],
    figures: [
      {
        src: "/infomap/images/state-network.svg",
        alt: "State network",
        caption:
          "A state network with five physical nodes and six state nodes, representing the same dynamics as the multilayer example.",
      },
    ],
    example: preview(exampleNetworks.states, 18),
  },
  {
    id: "OutputClu",
    chip: ".clu",
    side: "output",
    title: "Cluster file",
    tag: "-o clu",
    description:
      "Use .clu when you need a compact node-to-module assignment. This is usually the easiest output for downstream analysis.",
    details: [
      "By default, .clu outputs the top-level module assignments. To specify another level, use --clu-level <i>.",
      "If the .clu file is used as an input clustering to Infomap, the flow column is ignored and may be omitted.",
    ],
    example: outputExamples.clu,
  },
  {
    id: "OutputTree",
    chip: ".tree",
    side: "output",
    title: "Tree",
    tag: "-o tree",
    description:
      "Use .tree when you need the full hierarchy. Each row contains the module path, node flow, node name, and node id.",
    details: [
      "Module assignments are colon-separated from coarse to fine level. Modules within each level are sorted by the total flow of the nodes they contain.",
      "The integer after the last colon is the rank within the finest-level module. The decimal number is the steady-state probability of the random walker in that node.",
    ],
    example: outputExamples.tree,
  },
  {
    id: "OutputFtree",
    chip: ".ftree",
    side: "output",
    title: "Flow tree",
    tag: "-o ftree",
    description:
      "Use .ftree when you need the hierarchy plus flow links inside each module.",
    details: [
      "It extends .tree with *Links sections for child-node flow within modules. The first line states whether the links are undirected or directed.",
      "Links entering or leaving a module are not listed directly, but the corresponding flow is aggregated into enterFlow and exitFlow.",
    ],
    example: preview(outputExamples.ftreeLinks, 18),
  },
  {
    id: "OutputNewick",
    chip: ".nwk",
    side: "output",
    title: "Newick",
    tag: "-o newick",
    description:
      "Use Newick when you want to inspect or process the hierarchy with standard tree tooling.",
    details: [
      "The format is compact and useful for dendrogram or phylogenetic-style tools that understand parenthesized tree structure.",
    ],
    example: outputExamples.newick,
  },
  {
    id: "OutputJson",
    chip: ".json",
    side: "output",
    title: "JSON",
    tag: "-o json",
    description: "Use JSON when integrating Infomap output into applications.",
    details: [
      "JSON preserves structured metadata and avoids parsing text formats. It is the best output when another app or pipeline will consume the result directly.",
    ],
    example: preview(outputExamples.json, 18),
  },
];

const inputFormats = formats.filter((format) => format.side === "input");
const outputFormats = formats.filter((format) => format.side === "output");

type RailItem =
  | { kind: "heading"; label: string; id?: never; href?: never }
  | { kind?: never; id: string; label: string; href?: string };

const railItems: RailItem[] = [
  { kind: "heading", label: "Input" },
  ...inputFormats.map(({ id, title }) => ({ id, label: title })),
  { kind: "heading", label: "Output" },
  ...outputFormats.map(({ id, title }) => ({ id, label: title })),
  { id: "OutputHeader", label: "Output header" },
  { id: "CodelengthSavings", label: "Codelength savings" },
  { id: "PhysicalAndStateOutput", label: "Physical/state output" },
  { kind: "heading", label: "Read next" },
  { id: "HowItWorksNext", label: "How it works", href: "/how-it-works" },
];

function CodeBlock({ children }) {
  const [copied, setCopied] = useState(false);
  const text = Array.isArray(children) ? children.join("") : String(children);

  return (
    <Box position="relative" mt={4}>
      <Box
        bg="gray.100"
        borderWidth="1px"
        borderColor="gray.200"
        borderRadius="md"
        p={4}
        overflowX="auto"
      >
        <chakra.pre
          m={0}
          fontFamily="monospace"
          fontSize="sm"
          lineHeight={1.6}
          whiteSpace="pre-wrap"
        >
          {children}
        </chakra.pre>
      </Box>
      <Button
        type="button"
        variant="surface"
        size="xs"
        position="absolute"
        top={2}
        right={2}
        onClick={async () => {
          await navigator?.clipboard?.writeText(text);
          setCopied(true);
          window.setTimeout(() => setCopied(false), 1400);
        }}
      >
        {copied ? <LuCheck /> : <LuCopy />}
        {copied ? "Copied" : "Copy"}
      </Button>
    </Box>
  );
}

function FigureBlock({ figure }) {
  return (
    <Box
      as="figure"
      bg="gray.50"
      borderWidth="1px"
      borderColor="gray.200"
      borderRadius="md"
      p={{ base: 4, md: 5 }}
      m={0}
      maxW="100%"
      overflow="hidden"
    >
      <chakra.img
        src={figure.src}
        alt={figure.alt}
        maxW={{ base: figure.maxW ?? "18rem", md: figure.maxW ?? "100%" }}
        w="100%"
        display="block"
        mx="auto"
      />
      <Text
        as="figcaption"
        color="gray.600"
        fontSize="sm"
        lineHeight={1.6}
        mt={3}
        mb={0}
      >
        {figure.caption}
      </Text>
    </Box>
  );
}

function FormatDescription({ format }) {
  return (
    <Stack gap={3}>
      <Text color="gray.600" fontSize="sm" mb={0}>
        {format.description}
      </Text>

      {format.details?.map((detail) => (
        <Text key={detail} color="gray.600" fontSize="sm" mb={0}>
          {detail}
        </Text>
      ))}
    </Stack>
  );
}

function FormatCard({ format }) {
  return (
    <Box
      as="article"
      id={format.id}
      bg="white"
      borderWidth="1px"
      borderColor="gray.200"
      borderRadius="md"
      p={{ base: 5, md: 6 }}
      scrollMarginTop="6rem"
      minW={0}
      maxW="100%"
    >
      <Flex
        justify="space-between"
        align={{ base: "flex-start", md: "baseline" }}
        gap={3}
        direction={{ base: "column", md: "row" }}
        mb={2}
      >
        <Heading as="h3" size="sm">
          {format.title}
        </Heading>
        <Flex gap={2} flexWrap="wrap">
          <Box
            as="span"
            bg="gray.100"
            color="gray.600"
            borderRadius="sm"
            px={2}
            py={1}
            fontFamily="monospace"
            fontSize="xs"
          >
            {format.chip}
          </Box>
          <Box
            as="span"
            bg="gray.100"
            color="gray.600"
            borderRadius="sm"
            px={2}
            py={1}
            fontFamily="monospace"
            fontSize="xs"
          >
            {format.tag}
          </Box>
        </Flex>
      </Flex>

      {format.figures ? (
        <Grid
          templateColumns={{ base: "1fr", md: "3fr 2fr" }}
          gap={5}
          alignItems="start"
          minW={0}
        >
          <FormatDescription format={format} />
          <Stack gap={3} minW={0}>
            {format.figures.map((figure) => (
              <FigureBlock key={figure.src} figure={figure} />
            ))}
          </Stack>
        </Grid>
      ) : (
        <FormatDescription format={format} />
      )}

      <CodeBlock>{format.example}</CodeBlock>
    </Box>
  );
}

const FormatsPage: NextPage = () => {
  const [active, setActive] = useState("InputLinkList");
  const [showAnnotations, setShowAnnotations] = useState(true);

  return (
    <Container>
      <Grid
        templateColumns={{ base: "minmax(0, 1fr)", lg: "13rem minmax(0, 1fr)" }}
        gap={{ base: 8, lg: 12 }}
        alignItems="start"
        mt={8}
        minW={0}
      >
        <Box
          as="aside"
          display={{ base: "none", lg: "block" }}
          position="sticky"
          top="5rem"
        >
          <Text
            color="gray.500"
            fontFamily="monospace"
            fontSize="xs"
            letterSpacing="0.1em"
            textTransform="uppercase"
            mb={3}
          >
            On this page
          </Text>
          <Box borderLeftWidth="1px" borderLeftColor="gray.300">
            {railItems.map((item, index) =>
              item.kind === "heading" ? (
                <Text
                  key={`${item.label}-${index}`}
                  color="gray.500"
                  fontSize="xs"
                  letterSpacing="0.08em"
                  textTransform="uppercase"
                  px={4}
                  pt={index === 0 ? 2 : 4}
                  pb={1}
                  mb={0}
                >
                  {item.label}
                </Text>
              ) : item.href ? (
                <CkLink
                  key={item.id}
                  asChild
                  display="block"
                  color={active === item.id ? "gray.900" : "gray.500"}
                  fontWeight={active === item.id ? 700 : 400}
                  borderLeftWidth="2px"
                  borderLeftColor={
                    active === item.id ? "red.600" : "transparent"
                  }
                  ml="-1px"
                  px={4}
                  py={1.5}
                  fontSize="sm"
                  textDecoration="none"
                >
                  <NextLink href={item.href}>{item.label}</NextLink>
                </CkLink>
              ) : (
                <CkLink
                  key={item.id}
                  href={`#${item.id}`}
                  display="block"
                  color={active === item.id ? "gray.900" : "gray.500"}
                  fontWeight={active === item.id ? 700 : 400}
                  borderLeftWidth="2px"
                  borderLeftColor={
                    active === item.id ? "red.600" : "transparent"
                  }
                  ml="-1px"
                  px={4}
                  py={1.5}
                  fontSize="sm"
                  textDecoration="none"
                  onClick={() => setActive(item.id)}
                >
                  {item.label}
                </CkLink>
              ),
            )}
          </Box>
        </Box>

        <Box as="main" minW={0}>
          <Text color="gray.500" fontSize="sm" mb={2}>
            Documentation
          </Text>
          <Heading as="h1" size="lg" mb={4} id="Formats">
            Input & output formats
          </Heading>

          <Text
            color="gray.700"
            fontSize={{ base: "md", md: "lg" }}
            maxW="42rem"
          >
            Infomap reads and writes plain-text network files. Inputs are link
            lists or extensions of them; outputs describe the partition Infomap
            found, in flat or hierarchical form.
          </Text>

          <Box as="section" mb={10}>
            <Flex
              justify="space-between"
              align="baseline"
              gap={3}
              mb={3}
              minW={0}
            >
              <Heading as="h2" size="md" id="Input">
                Input
              </Heading>
              <Text color="gray.500" fontSize="sm" mb={0} flexShrink={0}>
                {inputFormats.length} formats
              </Text>
            </Flex>
            <Text color="gray.700" maxW="42rem">
              Start with a link list unless you need node names, bipartite flow,
              multilayer flow, or state nodes.
            </Text>

            <Stack gap={5}>
              {inputFormats.map((format) => (
                <FormatCard key={format.id} format={format} />
              ))}
            </Stack>

            <Box
              bg="white"
              borderWidth="1px"
              borderColor="red.100"
              borderRadius="md"
              p={4}
              mt={5}
            >
              <Text color="gray.700" fontSize="sm" mb={0}>
                <strong>Self-links:</strong> since v2.0.0 Infomap counts
                self-links by default. Pass <code>--no-self-links</code> to
                exclude them. For undirected networks, Infomap follows the
                convention of counting self-links once.
              </Text>
            </Box>
          </Box>

          <Box as="section" mb={10}>
            <Flex
              justify="space-between"
              align="baseline"
              gap={3}
              mb={3}
              minW={0}
            >
              <Heading as="h2" size="md" id="Output">
                Output
              </Heading>
              <Text color="gray.500" fontSize="sm" mb={0} flexShrink={0}>
                {outputFormats.length} formats
              </Text>
            </Flex>
            <Text color="gray.700" maxW="42rem">
              For most workflows use <code>.clu</code> for flat assignments and{" "}
              <code>.tree</code> for hierarchy. Write several outputs with{" "}
              <code>-o tree,ftree,clu</code>.
            </Text>

            <Stack gap={5}>
              {outputFormats.map((format) => (
                <FormatCard key={format.id} format={format} />
              ))}
            </Stack>
          </Box>

          <Box
            as="section"
            id="OutputHeader"
            bg="white"
            borderWidth="1px"
            borderColor="gray.200"
            borderRadius="md"
            p={{ base: 5, md: 6 }}
            mb={6}
            scrollMarginTop="6rem"
          >
            <Flex
              justify="space-between"
              align={{ base: "flex-start", md: "baseline" }}
              direction={{ base: "column", md: "row" }}
              gap={3}
              mb={3}
            >
              <Heading as="h2" size="md">
                Output header
              </Heading>
              <Button
                type="button"
                variant="surface"
                size="sm"
                onClick={() => setShowAnnotations(!showAnnotations)}
              >
                {showAnnotations ? "Hide annotations" : "Show annotations"}
              </Button>
            </Flex>
            <Text color="gray.600" fontSize="sm">
              Every output file starts with a header that records the run.
            </Text>
            <SimpleGrid columns={{ base: 1, md: showAnnotations ? 2 : 1 }}>
              <CodeBlock>{`# ${infomapVersionLabel}
# ./Infomap network.net . --ftree --clu
# started at 2026-05-05, 07:23:30
# completed in 0.114 s
# partitioned into 2 levels with 2 top modules
# codelength 2.32073 bits
# relative codelength savings 9.22792%`}</CodeBlock>
              {showAnnotations && (
                <Box
                  borderWidth="1px"
                  borderColor="gray.200"
                  borderRadius="md"
                  p={4}
                  fontSize="sm"
                  color="gray.600"
                >
                  <Stack gap={2}>
                    <Text mb={0}>Infomap version</Text>
                    <Text mb={0}>Exact command-line invocation</Text>
                    <Text mb={0}>Run timestamp</Text>
                    <Text mb={0}>Wall time</Text>
                    <Text mb={0}>Hierarchy depth and top-level count</Text>
                    <Text color="gray.900" fontWeight={700} mb={0}>
                      Total description length
                    </Text>
                    <Text color="gray.900" fontWeight={700} mb={0}>
                      Savings versus one-level baseline
                    </Text>
                  </Stack>
                </Box>
              )}
            </SimpleGrid>
          </Box>

          <Box
            as="section"
            id="CodelengthSavings"
            bg="white"
            borderWidth="1px"
            borderColor="gray.200"
            borderRadius="md"
            p={{ base: 5, md: 6 }}
            mb={6}
            scrollMarginTop="6rem"
          >
            <Heading as="h2" size="md" mb={3}>
              Codelength savings
            </Heading>
            <Text color="gray.600" fontSize="sm" maxW="38rem">
              The relative savings measures how much shorter Infomap&apos;s
              modular description is compared to the one-level baseline. Higher
              means stronger modular structure.
            </Text>
            <Box textAlign="center" py={3} fontSize={{ base: "lg", md: "xl" }}>
              <TeX math="S_L = 1 - \frac{L}{L_1}" block />
            </Box>
            <Text color="gray.500" fontSize="sm" textAlign="center" mb={0}>
              where <TeX>L</TeX> is the codelength and <TeX>L_1</TeX> is the
              one-level codelength.
            </Text>
          </Box>

          <Box
            as="section"
            id="PhysicalAndStateOutput"
            bg="white"
            borderWidth="1px"
            borderColor="gray.200"
            borderRadius="md"
            p={{ base: 5, md: 6 }}
            mb={12}
            scrollMarginTop="6rem"
          >
            <Heading as="h2" size="md" mb={3}>
              Physical and state-level output
            </Heading>
            <Grid
              templateColumns={{ base: "1fr", md: "3fr 2fr" }}
              gap={5}
              alignItems="start"
            >
              <Text color="gray.600" fontSize="sm" mb={0}>
                For ordinary networks, output rows refer to physical nodes. For
                memory, state, or multilayer networks, Infomap can also write
                state-level outputs. State-level files keep internal state nodes
                separate; physical outputs merge states that represent the same
                physical node when possible. Higher-order networks write two
                files for each of <code>clu</code>, <code>tree</code>, and{" "}
                <code>ftree</code>; the extra file has <code>_states</code>{" "}
                appended before the extension.
              </Text>
              <FigureBlock
                figure={{
                  src: "/infomap/images/physical-and-state-nodes.svg",
                  alt: "Physical and state nodes in output",
                  caption:
                    "Network flows at different modular levels. Large circles represent physical nodes, small circles represent state nodes, and dashed areas represent modules.",
                }}
              />
            </Grid>
          </Box>

          <Box
            as="section"
            id="ReadNext"
            bg="white"
            borderWidth="1px"
            borderColor="gray.200"
            borderRadius="md"
            p={{ base: 5, md: 6 }}
            mb={12}
            scrollMarginTop="6rem"
          >
            <Heading as="h2" size="md" mb={3}>
              Read next
            </Heading>
            <Flex gap={4} flexWrap="wrap">
              <CkLink asChild fontWeight={600}>
                <NextLink href="/how-it-works">
                  How Infomap works <LuArrowRight />
                </NextLink>
              </CkLink>
            </Flex>
          </Box>
        </Box>
      </Grid>
    </Container>
  );
};

export default FormatsPage;
